require('nvim-ts-autotag').setup({
    filetypes = {
        'hbs',
        'jsx',
        'xml',
        'tsx',
        'vue',
        'html',
        'svelte',
        'glimmer',
        'rescript',
        'markdown',
        'javascript',
        'handlebars',
        'typescript',
        'javascriptreact',
        'typescriptreact',
    },
})
